package me.luligabi.elementalcreepers.common;

import draylar.omegaconfig.api.Comment;
import draylar.omegaconfig.api.Config;
import org.apache.http.cookie.Cookie;
import org.jetbrains.annotations.Nullable;

public class ModConfig implements Config {


    // Water Creeper
    @Comment(value = "Whether or not Water Creepers can spawn.")
    public boolean waterCreeperEnabled = true;

    @Comment(value = "The radius of the water generated by a Water Creeper.")
    public float waterCreeperRadius = 3;

    @Comment(value = "How often Water Creepers will spawn (Vanilla Creeper's value is 100).")
    public int waterCreeperSpawnRate = 20;


    // Fire Creeper
    @Comment(value = "Whether or not Fire Creepers can spawn.")
    public boolean fireCreeperEnabled = true;

    @Comment(value = "The radius of the fire generated by a Fire Creeper.")
    public float fireCreeperRadius = 3;

    @Comment(value = "How often Fire Creepers will spawn (Vanilla Creeper's value is 100).")
    public int fireCreeperSpawnRate = 25;


    // Earth Creeper
    @Comment(value = "Whether or not Earth Creepers can spawn.")
    public boolean earthCreeperEnabled = true;

    @Comment(value = "The radius of the dirt generated by an Earth Creeper.")
    public float earthCreeperRadius = 5;

    @Comment(value = "How often Earth Creepers will spawn (Vanilla Creeper's value is 100).")
    public int earthCreeperSpawnRate = 15;


    // Air Creeper
    @Comment(value = "Whether or not Air Creepers can spawn.")
    public boolean airCreeperEnabled = true;

    @Comment(value = "How high in the air an Air Creeper can throw entities.")
    public float airCreeperRadius = 1.75F;

    @Comment(value = "How often Air Creepers will spawn (Vanilla Creeper's value is 100).")
    public int airCreeperSpawnRate = 20;


    // Electric Creeper
    @Comment(value = "Whether or not Electric Creepers can spawn.")
    public boolean electricCreeperEnabled = true;

    @Comment(value = "How often Electric Creepers will spawn (Vanilla Creeper's value is 100).")
    public int electricCreeperSpawnRate = 7;


    // Light Creeper
    @Comment(value = "Whether or not Light Creepers can spawn.")
    public boolean lightCreeperEnabled = true;

    @Comment(value = "The radius of the Glowstone generated by a Light Creeper.")
    public float lightCreeperRadius = 4;

    @Comment(value = "How often Light Creepers will spawn (Vanilla Creeper's value is 100).")
    public int lightCreeperSpawnRate = 20;


    // Dark Creeper
    @Comment(value = "Whether or not Dark Creepers can spawn.")
    public boolean darkCreeperEnabled = true;

    @Comment(value = "The radius of the light-source blocks removed by a Dark Creeper's explosion.")
    public float darkCreeperRadius = 4;

    @Comment(value = "How often Dark Creepers will spawn (Vanilla Creeper's value is 100).")
    public int darkCreeperSpawnRate = 12;


    // Ice Creeper
    @Comment(value = "Whether or not Ice Creepers can spawn.")
    public boolean iceCreeperEnabled = true;

    @Comment(value = "The radius of the snow generated by an Ice Creeper.")
    public float iceCreeperRadius = 4;

    @Comment(value = "How often Ice Creepers will spawn (Vanilla Creeper's value is 100).")
    public int iceCreeperSpawnRate = 20;


    // Magma Creeper
    @Comment(value = "Whether or not Magma Creepers can spawn.")
    public boolean magmaCreeperEnabled = true;

    @Comment(value = "The radius of the lava generated by a Magma Creeper.")
    public float magmaCreeperRadius = 4;

    @Comment(value = "How often Magma Creepers will spawn (Vanilla Creeper's value is 100).")
    public int magmaCreeperSpawnRate = 25;


    // Hydrogen Creeper
    @Comment(value = "Whether or not Hydrogen Creepers can spawn.")
    public boolean hydrogenCreeperEnabled = true;

    @Comment(value = "The radius of the lava generated by an Hydrogen Creeper.")
    public float hydrogenCreeperRadius = 7;

    @Comment(value = "How often Hydrogen Creepers will spawn (Vanilla Creeper's value is 100).")
    public int hydrogenCreeperSpawnRate = 3;


    // Reverse Creeper
    @Comment(value = "Whether or not Hydrogen Creepers can spawn.")
    public boolean reverseCreeperEnabled = true;

    @Comment(value = "The radius of the blocks shifted by a Reverse Creeper.")
    public float reverseCreeperRadius = 3.75F;

    @Comment(value = "How often Reverse Creepers will spawn (Vanilla Creeper's value is 100).")
    public int reverseCreeperSpawnRate = 10;


    // Miner Creeper
    @Comment(value = "Whether or not Miner Creepers can spawn.")
    public boolean minerCreeperEnabled = true;

    @Comment(value = "The radius of the blocks removed by a Miner Creeper.")
    public float minerCreeperRadius = 3.75F;

    @Comment(value = "How often Miner Creepers will spawn (Vanilla Creeper's value is 100).")
    public int minerCreeperSpawnRate = 15;


    // Illusion Creeper
    @Comment(value = "Whether or not Illusion Creepers can spawn.")
    public boolean illusionCreeperEnabled = true;

    @Comment(value = "How often Illusion Creepers will spawn (Vanilla Creeper's value is 100).")
    public int illusionCreeperSpawnRate = 10;


    // Firework Creeper
    @Comment(value = "Whether or not Firework Creepers can spawn.")
    public boolean fireworkCreeperEnabled = true;

    @Comment(value = "How often Firework Creepers will spawn (Vanilla Creeper's value is 100).")
    public int fireworkCreeperSpawnRate = 4;


    // Cookie Creeper
    @Comment(value = "Whether or not Cookie Creepers can spawn.")
    public boolean cookieCreeperEnabled = true;

    @Comment(value = "How often Cookie Creepers will spawn (Vanilla Creeper's value is 100).")
    public int cookieCreeperSpawnRate = 2;


    // Rainbow Creeper
    @Comment(value = "Whether or not Rainbow Creepers can spawn.")
    public boolean rainbowCreeperEnabled = true;

    @Comment(value = "How often Rainbow Creepers will spawn (Vanilla Creeper's value is 100).")
    public int rainbowCreeperSpawnRate = 1;


    @Override
    public String getName() {
        return getModid();
    }

    @Override
    public @Nullable String getModid() {
        return ElementalCreepers.MOD_ID;
    }

}